language: go
dist: xenial

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
